### ISSUE TITLE
Create a way to declaratively exclude modules/paths from babel-loader

### ISSUE THREAD

**Issue by PAkerstrand** [rocjs/roc-package-webpack#10]
We have some vendor files that are already webpacked, babelified etc. These files have a tendency to break if they run through `babel-loader` a second time. For the time being, we solve it like this in an action in our `roc.config.js`-file:

``` js
const babelLoader = rocBuilder.buildConfig.module.loaders.find((loaderConfig) => loaderConfig.id === 'babel');
if (babelLoader) {
    if (!babelLoader.exclude) {
        babelLoader.exclude = [];
    }
    if (!Array.isArray(babelLoader.exclude)) {
        babelLoader.exclude = [babelLoader.exclude];
    }
    babelLoader.exclude = babelLoader.exclude.concat([
        path.resolve('./src/vendor'),
    ]);
}

return rocBuilder;
```

It would be really neat if the boilerplate can be hidden, and Roc provided a way to declaratively add paths/RegExps/modules to be hidden from the `babel-loader`:

``` js
settings: {
  build: {
    loaders: {
      babel: {
        exclude: [path.resolve('./src/vendor')]
      }
    }
  }
}
```

**Comment by dlmr** [comment]
This issue has been moved into the mono repository rocjs/extensions#23.
