### ISSUE TITLE
Support configured externals in webpack

### ISSUE THREAD

**Issue by andreasrs** [rocjs/roc-package-webpack#17]
Our plugin (rocExportWebpackPlugin) that handles resolving for exported dependencies should also respect any declared `externals`. This is required in order for things like Enzyme to work (https://github.com/airbnb/enzyme/blob/master/docs/guides/webpack.md)

Webpack externals: https://webpack.github.io/docs/configuration.html#externals

**Comment by dlmr** [comment]
Seems like we also do not respect `resolve.alias` in the Webpack configuration, something we should absolutely do.
